linters:
  enable:
    - govet         # Анализ кода Go для обнаружения потенциальных ошибок
    - gofmt         # Форматирование исходного кода Go по стандартному стилю
    - goimports     # Автоматическое добавление и удаление импорта в Go-коде
    - staticcheck   # Расширенная статическая проверка кода Go на наличие ошибок и антипаттернов
    - ineffassign   # Поиск неиспользуемых переменных, которым были присвоены значения
    - errcheck      # Проверка того, что ошибки, возвращаемые функциями, всегда обрабатываются
    - gosimple      # Обнаружение упрощений в коде, которые могут улучшить его читаемость
    - typecheck     # Проверка типов в Go-коде
    - unused        # Обнаружение неиспользуемых переменных, констант, типов и функций
    - makezero      # Поиск мест, где можно использовать встроенные функции инициализации
    - whitespace    # Проверка на наличие ненужных пробелов в коде

run:
  timeout: 5m         # Максимальное время выполнения линтеров — 5 минут
  tests: true         # Включение проверки тестовых файлов

issues:
  exclude-dirs:
    - "/migrations"   # Исключение директории 'migrations' из анализа
    - "pkg/"          # Исключение директории 'pkg' из анализа
  exclude-rules:
    - linters:
        - errcheck    # Отключение правила 'errcheck' для сообщений "error is not checked"
      text: "error is not checked"
  max-issues-per-linter: 0   # Нет ограничения на количество проблем для каждого линтера
  max-same-issues: 0         # Нет ограничения на количество одинаковых проблем

formatters:
  - name: colored-line-number  # Форматтер с выводом цветных номеров строк
