version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate_tool
    volumes:
      - ./migrations:/migrations
    command: ["-help"]
    depends_on:
      - postgres

volumes:
  postgres_data: